# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ajemraou <ajemraou@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/29 17:03:10 by ajemraou          #+#    #+#              #
#    Updated: 2022/10/29 17:07:24 by ajemraou         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = g++

CFLAGE = -Wall -Wextra -Werror

SRC =	main.cpp \
		Account.cpp

NAME = Account

all :
	@$(CC) $(CFLAGE) $(SRC) -o $(NAME)

clean :
	@rm -f $(NAME)

fclean : clean

re : fclea all