# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ajemraou <ajemraou@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/20 10:19:27 by ajemraou          #+#    #+#              #
#    Updated: 2022/10/24 18:20:51 by ajemraou         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = g++

CFLAGE = -Wall -Wextra -Werror -std=c++98

SRC =	megaphone.cpp \
	

NAME = megaphone

all :
	@$(CC) $(SRC) -o $(NAME)

clean :
	@rm -f $(NAME)

fclean : clean

re : fclean all